---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cray-hpe-com-v1alpha1-lustrefilesystem
  failurePolicy: Fail
  name: vlustrefilesystem.kb.io
  rules:
  - apiGroups:
    - cray.hpe.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lustrefilesystems
  sideEffects: None
