# permissions for end users to view lustrefilesystems.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lustrefilesystem-viewer-role
rules:
- apiGroups:
  - cray.hpe.com
  resources:
  - lustrefilesystems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cray.hpe.com
  resources:
  - lustrefilesystems/status
  verbs:
  - get
