
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - cray.hpe.com
  resources:
  - lustrefilesystems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cray.hpe.com
  resources:
  - lustrefilesystems/finalizers
  verbs:
  - update
- apiGroups:
  - cray.hpe.com
  resources:
  - lustrefilesystems/status
  verbs:
  - get
  - patch
  - update
