apiVersion: v1
kind: Namespace
metadata:
  name: nnf-daffy-lustre
---
apiVersion: lus.cray.hpe.com/v1alpha1
kind: LustreFileSystem
metadata:
  name: w0-lustre-fs
  namespace: nnf-daffy-lustre
spec:
  name: w0
  mgsNids: rabbit-03@tcp
  mountRoot: /lus/w0
  namespaces:
    nnf-daffy-lustre:
      modes:
        - ReadWriteMany




