apiVersion: lus.cray.hpe.com/v1alpha1
kind: LustreFileSystem
metadata:
  name: lustrefilesystem-sample-maui
  namespace: nnf-lustre-fs-system
spec:
  name: maui
  mgsNids: 172.0.0.0@tcp
  mountRoot: /lus/maui
  namespaces:
    default:
      modes:
        - ReadWriteMany
