//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright 2025 Hewlett Packard Enterprise Development LP
 * Other additional copyright holders may be indicated within.
 *
 * The entirety of this work is licensed under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 *
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1beta1 "github.com/NearNodeFlash/lustre-fs-operator/api/v1beta1"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*LustreFileSystem)(nil), (*v1beta1.LustreFileSystem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LustreFileSystem_To_v1beta1_LustreFileSystem(a.(*LustreFileSystem), b.(*v1beta1.LustreFileSystem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.LustreFileSystem)(nil), (*LustreFileSystem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LustreFileSystem_To_v1alpha1_LustreFileSystem(a.(*v1beta1.LustreFileSystem), b.(*LustreFileSystem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LustreFileSystemList)(nil), (*v1beta1.LustreFileSystemList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LustreFileSystemList_To_v1beta1_LustreFileSystemList(a.(*LustreFileSystemList), b.(*v1beta1.LustreFileSystemList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.LustreFileSystemList)(nil), (*LustreFileSystemList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LustreFileSystemList_To_v1alpha1_LustreFileSystemList(a.(*v1beta1.LustreFileSystemList), b.(*LustreFileSystemList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LustreFileSystemNamespaceAccessStatus)(nil), (*v1beta1.LustreFileSystemNamespaceAccessStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LustreFileSystemNamespaceAccessStatus_To_v1beta1_LustreFileSystemNamespaceAccessStatus(a.(*LustreFileSystemNamespaceAccessStatus), b.(*v1beta1.LustreFileSystemNamespaceAccessStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.LustreFileSystemNamespaceAccessStatus)(nil), (*LustreFileSystemNamespaceAccessStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LustreFileSystemNamespaceAccessStatus_To_v1alpha1_LustreFileSystemNamespaceAccessStatus(a.(*v1beta1.LustreFileSystemNamespaceAccessStatus), b.(*LustreFileSystemNamespaceAccessStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LustreFileSystemNamespaceSpec)(nil), (*v1beta1.LustreFileSystemNamespaceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LustreFileSystemNamespaceSpec_To_v1beta1_LustreFileSystemNamespaceSpec(a.(*LustreFileSystemNamespaceSpec), b.(*v1beta1.LustreFileSystemNamespaceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.LustreFileSystemNamespaceSpec)(nil), (*LustreFileSystemNamespaceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LustreFileSystemNamespaceSpec_To_v1alpha1_LustreFileSystemNamespaceSpec(a.(*v1beta1.LustreFileSystemNamespaceSpec), b.(*LustreFileSystemNamespaceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LustreFileSystemNamespaceStatus)(nil), (*v1beta1.LustreFileSystemNamespaceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LustreFileSystemNamespaceStatus_To_v1beta1_LustreFileSystemNamespaceStatus(a.(*LustreFileSystemNamespaceStatus), b.(*v1beta1.LustreFileSystemNamespaceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.LustreFileSystemNamespaceStatus)(nil), (*LustreFileSystemNamespaceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LustreFileSystemNamespaceStatus_To_v1alpha1_LustreFileSystemNamespaceStatus(a.(*v1beta1.LustreFileSystemNamespaceStatus), b.(*LustreFileSystemNamespaceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LustreFileSystemSpec)(nil), (*v1beta1.LustreFileSystemSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LustreFileSystemSpec_To_v1beta1_LustreFileSystemSpec(a.(*LustreFileSystemSpec), b.(*v1beta1.LustreFileSystemSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.LustreFileSystemSpec)(nil), (*LustreFileSystemSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LustreFileSystemSpec_To_v1alpha1_LustreFileSystemSpec(a.(*v1beta1.LustreFileSystemSpec), b.(*LustreFileSystemSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LustreFileSystemStatus)(nil), (*v1beta1.LustreFileSystemStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LustreFileSystemStatus_To_v1beta1_LustreFileSystemStatus(a.(*LustreFileSystemStatus), b.(*v1beta1.LustreFileSystemStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.LustreFileSystemStatus)(nil), (*LustreFileSystemStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LustreFileSystemStatus_To_v1alpha1_LustreFileSystemStatus(a.(*v1beta1.LustreFileSystemStatus), b.(*LustreFileSystemStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_LustreFileSystem_To_v1beta1_LustreFileSystem(in *LustreFileSystem, out *v1beta1.LustreFileSystem, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_LustreFileSystemSpec_To_v1beta1_LustreFileSystemSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_LustreFileSystemStatus_To_v1beta1_LustreFileSystemStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LustreFileSystem_To_v1beta1_LustreFileSystem is an autogenerated conversion function.
func Convert_v1alpha1_LustreFileSystem_To_v1beta1_LustreFileSystem(in *LustreFileSystem, out *v1beta1.LustreFileSystem, s conversion.Scope) error {
	return autoConvert_v1alpha1_LustreFileSystem_To_v1beta1_LustreFileSystem(in, out, s)
}

func autoConvert_v1beta1_LustreFileSystem_To_v1alpha1_LustreFileSystem(in *v1beta1.LustreFileSystem, out *LustreFileSystem, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_LustreFileSystemSpec_To_v1alpha1_LustreFileSystemSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_LustreFileSystemStatus_To_v1alpha1_LustreFileSystemStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_LustreFileSystem_To_v1alpha1_LustreFileSystem is an autogenerated conversion function.
func Convert_v1beta1_LustreFileSystem_To_v1alpha1_LustreFileSystem(in *v1beta1.LustreFileSystem, out *LustreFileSystem, s conversion.Scope) error {
	return autoConvert_v1beta1_LustreFileSystem_To_v1alpha1_LustreFileSystem(in, out, s)
}

func autoConvert_v1alpha1_LustreFileSystemList_To_v1beta1_LustreFileSystemList(in *LustreFileSystemList, out *v1beta1.LustreFileSystemList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.LustreFileSystem)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_LustreFileSystemList_To_v1beta1_LustreFileSystemList is an autogenerated conversion function.
func Convert_v1alpha1_LustreFileSystemList_To_v1beta1_LustreFileSystemList(in *LustreFileSystemList, out *v1beta1.LustreFileSystemList, s conversion.Scope) error {
	return autoConvert_v1alpha1_LustreFileSystemList_To_v1beta1_LustreFileSystemList(in, out, s)
}

func autoConvert_v1beta1_LustreFileSystemList_To_v1alpha1_LustreFileSystemList(in *v1beta1.LustreFileSystemList, out *LustreFileSystemList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]LustreFileSystem)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_LustreFileSystemList_To_v1alpha1_LustreFileSystemList is an autogenerated conversion function.
func Convert_v1beta1_LustreFileSystemList_To_v1alpha1_LustreFileSystemList(in *v1beta1.LustreFileSystemList, out *LustreFileSystemList, s conversion.Scope) error {
	return autoConvert_v1beta1_LustreFileSystemList_To_v1alpha1_LustreFileSystemList(in, out, s)
}

func autoConvert_v1alpha1_LustreFileSystemNamespaceAccessStatus_To_v1beta1_LustreFileSystemNamespaceAccessStatus(in *LustreFileSystemNamespaceAccessStatus, out *v1beta1.LustreFileSystemNamespaceAccessStatus, s conversion.Scope) error {
	out.State = v1beta1.NamespaceAccessState(in.State)
	out.PersistentVolumeRef = (*v1.LocalObjectReference)(unsafe.Pointer(in.PersistentVolumeRef))
	out.PersistentVolumeClaimRef = (*v1.LocalObjectReference)(unsafe.Pointer(in.PersistentVolumeClaimRef))
	return nil
}

// Convert_v1alpha1_LustreFileSystemNamespaceAccessStatus_To_v1beta1_LustreFileSystemNamespaceAccessStatus is an autogenerated conversion function.
func Convert_v1alpha1_LustreFileSystemNamespaceAccessStatus_To_v1beta1_LustreFileSystemNamespaceAccessStatus(in *LustreFileSystemNamespaceAccessStatus, out *v1beta1.LustreFileSystemNamespaceAccessStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_LustreFileSystemNamespaceAccessStatus_To_v1beta1_LustreFileSystemNamespaceAccessStatus(in, out, s)
}

func autoConvert_v1beta1_LustreFileSystemNamespaceAccessStatus_To_v1alpha1_LustreFileSystemNamespaceAccessStatus(in *v1beta1.LustreFileSystemNamespaceAccessStatus, out *LustreFileSystemNamespaceAccessStatus, s conversion.Scope) error {
	out.State = NamespaceAccessState(in.State)
	out.PersistentVolumeRef = (*v1.LocalObjectReference)(unsafe.Pointer(in.PersistentVolumeRef))
	out.PersistentVolumeClaimRef = (*v1.LocalObjectReference)(unsafe.Pointer(in.PersistentVolumeClaimRef))
	return nil
}

// Convert_v1beta1_LustreFileSystemNamespaceAccessStatus_To_v1alpha1_LustreFileSystemNamespaceAccessStatus is an autogenerated conversion function.
func Convert_v1beta1_LustreFileSystemNamespaceAccessStatus_To_v1alpha1_LustreFileSystemNamespaceAccessStatus(in *v1beta1.LustreFileSystemNamespaceAccessStatus, out *LustreFileSystemNamespaceAccessStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_LustreFileSystemNamespaceAccessStatus_To_v1alpha1_LustreFileSystemNamespaceAccessStatus(in, out, s)
}

func autoConvert_v1alpha1_LustreFileSystemNamespaceSpec_To_v1beta1_LustreFileSystemNamespaceSpec(in *LustreFileSystemNamespaceSpec, out *v1beta1.LustreFileSystemNamespaceSpec, s conversion.Scope) error {
	out.Modes = *(*[]v1.PersistentVolumeAccessMode)(unsafe.Pointer(&in.Modes))
	return nil
}

// Convert_v1alpha1_LustreFileSystemNamespaceSpec_To_v1beta1_LustreFileSystemNamespaceSpec is an autogenerated conversion function.
func Convert_v1alpha1_LustreFileSystemNamespaceSpec_To_v1beta1_LustreFileSystemNamespaceSpec(in *LustreFileSystemNamespaceSpec, out *v1beta1.LustreFileSystemNamespaceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_LustreFileSystemNamespaceSpec_To_v1beta1_LustreFileSystemNamespaceSpec(in, out, s)
}

func autoConvert_v1beta1_LustreFileSystemNamespaceSpec_To_v1alpha1_LustreFileSystemNamespaceSpec(in *v1beta1.LustreFileSystemNamespaceSpec, out *LustreFileSystemNamespaceSpec, s conversion.Scope) error {
	out.Modes = *(*[]v1.PersistentVolumeAccessMode)(unsafe.Pointer(&in.Modes))
	return nil
}

// Convert_v1beta1_LustreFileSystemNamespaceSpec_To_v1alpha1_LustreFileSystemNamespaceSpec is an autogenerated conversion function.
func Convert_v1beta1_LustreFileSystemNamespaceSpec_To_v1alpha1_LustreFileSystemNamespaceSpec(in *v1beta1.LustreFileSystemNamespaceSpec, out *LustreFileSystemNamespaceSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_LustreFileSystemNamespaceSpec_To_v1alpha1_LustreFileSystemNamespaceSpec(in, out, s)
}

func autoConvert_v1alpha1_LustreFileSystemNamespaceStatus_To_v1beta1_LustreFileSystemNamespaceStatus(in *LustreFileSystemNamespaceStatus, out *v1beta1.LustreFileSystemNamespaceStatus, s conversion.Scope) error {
	out.Modes = *(*map[v1.PersistentVolumeAccessMode]v1beta1.LustreFileSystemNamespaceAccessStatus)(unsafe.Pointer(&in.Modes))
	return nil
}

// Convert_v1alpha1_LustreFileSystemNamespaceStatus_To_v1beta1_LustreFileSystemNamespaceStatus is an autogenerated conversion function.
func Convert_v1alpha1_LustreFileSystemNamespaceStatus_To_v1beta1_LustreFileSystemNamespaceStatus(in *LustreFileSystemNamespaceStatus, out *v1beta1.LustreFileSystemNamespaceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_LustreFileSystemNamespaceStatus_To_v1beta1_LustreFileSystemNamespaceStatus(in, out, s)
}

func autoConvert_v1beta1_LustreFileSystemNamespaceStatus_To_v1alpha1_LustreFileSystemNamespaceStatus(in *v1beta1.LustreFileSystemNamespaceStatus, out *LustreFileSystemNamespaceStatus, s conversion.Scope) error {
	out.Modes = *(*map[v1.PersistentVolumeAccessMode]LustreFileSystemNamespaceAccessStatus)(unsafe.Pointer(&in.Modes))
	return nil
}

// Convert_v1beta1_LustreFileSystemNamespaceStatus_To_v1alpha1_LustreFileSystemNamespaceStatus is an autogenerated conversion function.
func Convert_v1beta1_LustreFileSystemNamespaceStatus_To_v1alpha1_LustreFileSystemNamespaceStatus(in *v1beta1.LustreFileSystemNamespaceStatus, out *LustreFileSystemNamespaceStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_LustreFileSystemNamespaceStatus_To_v1alpha1_LustreFileSystemNamespaceStatus(in, out, s)
}

func autoConvert_v1alpha1_LustreFileSystemSpec_To_v1beta1_LustreFileSystemSpec(in *LustreFileSystemSpec, out *v1beta1.LustreFileSystemSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.MgsNids = in.MgsNids
	out.MountRoot = in.MountRoot
	out.StorageClassName = in.StorageClassName
	out.Namespaces = *(*map[string]v1beta1.LustreFileSystemNamespaceSpec)(unsafe.Pointer(&in.Namespaces))
	return nil
}

// Convert_v1alpha1_LustreFileSystemSpec_To_v1beta1_LustreFileSystemSpec is an autogenerated conversion function.
func Convert_v1alpha1_LustreFileSystemSpec_To_v1beta1_LustreFileSystemSpec(in *LustreFileSystemSpec, out *v1beta1.LustreFileSystemSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_LustreFileSystemSpec_To_v1beta1_LustreFileSystemSpec(in, out, s)
}

func autoConvert_v1beta1_LustreFileSystemSpec_To_v1alpha1_LustreFileSystemSpec(in *v1beta1.LustreFileSystemSpec, out *LustreFileSystemSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.MgsNids = in.MgsNids
	out.MountRoot = in.MountRoot
	out.StorageClassName = in.StorageClassName
	out.Namespaces = *(*map[string]LustreFileSystemNamespaceSpec)(unsafe.Pointer(&in.Namespaces))
	return nil
}

// Convert_v1beta1_LustreFileSystemSpec_To_v1alpha1_LustreFileSystemSpec is an autogenerated conversion function.
func Convert_v1beta1_LustreFileSystemSpec_To_v1alpha1_LustreFileSystemSpec(in *v1beta1.LustreFileSystemSpec, out *LustreFileSystemSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_LustreFileSystemSpec_To_v1alpha1_LustreFileSystemSpec(in, out, s)
}

func autoConvert_v1alpha1_LustreFileSystemStatus_To_v1beta1_LustreFileSystemStatus(in *LustreFileSystemStatus, out *v1beta1.LustreFileSystemStatus, s conversion.Scope) error {
	out.Namespaces = *(*map[string]v1beta1.LustreFileSystemNamespaceStatus)(unsafe.Pointer(&in.Namespaces))
	return nil
}

// Convert_v1alpha1_LustreFileSystemStatus_To_v1beta1_LustreFileSystemStatus is an autogenerated conversion function.
func Convert_v1alpha1_LustreFileSystemStatus_To_v1beta1_LustreFileSystemStatus(in *LustreFileSystemStatus, out *v1beta1.LustreFileSystemStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_LustreFileSystemStatus_To_v1beta1_LustreFileSystemStatus(in, out, s)
}

func autoConvert_v1beta1_LustreFileSystemStatus_To_v1alpha1_LustreFileSystemStatus(in *v1beta1.LustreFileSystemStatus, out *LustreFileSystemStatus, s conversion.Scope) error {
	out.Namespaces = *(*map[string]LustreFileSystemNamespaceStatus)(unsafe.Pointer(&in.Namespaces))
	return nil
}

// Convert_v1beta1_LustreFileSystemStatus_To_v1alpha1_LustreFileSystemStatus is an autogenerated conversion function.
func Convert_v1beta1_LustreFileSystemStatus_To_v1alpha1_LustreFileSystemStatus(in *v1beta1.LustreFileSystemStatus, out *LustreFileSystemStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_LustreFileSystemStatus_To_v1alpha1_LustreFileSystemStatus(in, out, s)
}
